[package]
name = "rkave-aoc-2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
regex = "1"
anyhow = "1"
itertools = "0.10"
rayon = "1.5.3"
fxhash = "0.2.1"

[dependencies.reqwest]
version = "0"
features = ["cookies", "blocking"]